export const funMessage = [
  { message: "Are Yaar, Login karna bhul gaye?", icon: "🤔" },
  { message: "Are, Login karlo yaar", icon: "😅" },
  { message: "Ab to login karna pdega", icon: "😐" },
  { message: "Login karoge tabhi agla step milega!", icon: "🪜" },
  { message: "Login nahi kiya to kya kiya?", icon: "😕" },
  { message: "Kya mast dekh rahe ho! Login to karlo.", icon: "👀" },
  { message: "Login karo, warna hum login karwa denge!", icon: "😂" },
  { message: "Itna mat socho, login hi to karna hai!", icon: "🧠" },
  { message: "Bina login sab bekar hai!", icon: "🙃" },
  { message: "Aapka login hi aapki pehchaan hai.", icon: "🆔" },
  { message: "Pehle login, baad mein aur kuch socho.", icon: "📝" },
  { message: "Login karna compulsory hai, yaar!", icon: "✋" },
  { message: "Nahi karoge to kaise chalega? Login karlo!", icon: "😜" },
  { message: "Login nahi kiya to kaise chalega kaam?", icon: "💼" },
  { message: "Aapko bas ek kaam karna hai: Login!", icon: "✅" },
  { message: "Login karne mein kya jaata hai?", icon: "🙄" },
  { message: "Bhai, pehle login phir baatein!", icon: "👨‍💻" },
  { message: "Are bhai, login karne ka mann nahi hai kya?", icon: "😏" },
  { message: "Login ka button dikh raha hai? Click karo!", icon: "🔘" },
  { message: "Login nahi kiya to kuch nahi milega!", icon: "🚫" },
  {
    message: "Aap login nahi karenge, hum aapke peeche pad jayenge!",
    icon: "😆",
  },
  { message: "Login karo aur agla level unlock karo!", icon: "🕹️" },
  { message: "Yaar, login karo aur mazze lo!", icon: "😎" },
  { message: "Login nahi karoge to kaise chalega? Try karo!", icon: "💡" },
  { message: "Login ka button kaafi lonely hai, click kar do!", icon: "🖱️" },
];

